displayName: Traefik AuthZ Gateway
type: middleware
iconPath: .assets/icon.png

import: github.com/momayyez/authz-traefik-gateway

summary: Authorization middleware for validating Keycloak permissions using UMA 2.0

testData:
  TokenEndpoint: "http://keycloak:8080/realms/demo/protocol/openid-connect/token"
  ClientID: "traefik-gateway-client"
