displayName: Traefik AuthZ Gateway
type: middleware
iconPath: .assets/icon.png

import: github.com/momayyez/authztraefikgateway

summary: 'Authorization middleware for validating Keycloak permissions'

testData:
  keycloak_url: http://keycloak:8080/auth/realms/mingyang/protocol/openid-connect/token
  keycloak_client_id: traefik-gateway-client
